In [5]:
import numpy as np

In [112]:
def calcular_sindrome(patron_error, matriz_Ht):
    sindrome = []
    detectable = []
    for i in patron_error:
        valor = []
        i2 = [np.float64(j) for j in np.array(list(i))]
        for x in range(len(matriz_Ht[0])):
            multiply_ih = i2*matriz_Ht[:,x]
            valid = np.count_nonzero(multiply_ih == 1)
            if valid%2 != 0:
                valor.append(1)
            else:
                valor.append(0)
        sindrome.append(valor)
        if valor == [0, 0, 0]:
            detectable.append("no")
        else:
            detectable.append("si")
    return sindrome, detectable
    

In [115]:
n=7
k=4
matriz_P = np.array([[1,1,0],[0,1,1],[1,1,1],[1,0,1]])
matriz_Ik= np.identity(k)
matriz_G = np.concatenate((matriz_P.T,matriz_Ik.T),axis=0).T
matriz_H = np.concatenate((matriz_Ik[:-1].T[:-1],matriz_P),axis=0).T
matriz_Ht = matriz_H.T

In [127]:
## calculo de patrones de error
patron_error = np.array(["{0:07b}".format(x) for x in range(128)])
cantidad_error = np.array([x.count('1') for x in patron_error])
sindrome, detectable = calcular_sindrome(patron_error,matriz_Ht)
corregibles = ["si" if x<2 else "no" for x in cantidad_error]


In [128]:
corregibles

['si',
 'si',
 'si',
 'no',
 'si',
 'no',
 'no',
 'no',
 'si',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'si',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'si',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'si',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no']

In [97]:
x1 = np.array(list(patron_error[-1]))
x = [np.float64(i) for i in x1]
print(x)
print(matriz_Ht)
a = x*matriz_Ht[:,0]
a = np.count_nonzero(a == 1)
print(a%2)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]
 [0. 1. 1.]
 [1. 1. 1.]
 [1. 0. 1.]]
0


In [72]:
print(np.isin(x,1))
print(np.isin(matriz_Ht[:,0],1))
print(np.isin(matriz_Ht[:,1],1))
print(np.isin(matriz_Ht[:,2],1))

print(np.isin(x,1) | np.isin(matriz_Ht[:,0],1))
print(np.isin(x,1) | np.isin(matriz_Ht[:,1],1))
print(np.isin(x,1) | np.isin(matriz_Ht[:,2],1))

[False False False False False False  True]
[ True False False  True False  True  True]
[False  True False  True  True  True False]
[False False  True False  True  True  True]
[ True False False  True False  True  True]
[False  True False  True  True  True  True]
[False False  True False  True  True  True]
